name: Trigger auto deployment for container-app-z2uld2xqpurgo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-z2uld2xqpurgo-AutoDeployTrigger-3ef7851a-d040-4e73-a8f1-026839246c4c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZ2ULD2XQPURGO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZ2ULD2XQPURGO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZ2ULD2XQPURGO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPZ2ULD2XQPURGO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZ2ULD2XQPURGO_REGISTRY_PASSWORD }}
          containerAppName: container-app-z2uld2xqpurgo
          resourceGroup: chatbotreactnodejsad2abf34
          imageToBuild: default/container-app-z2uld2xqpurgo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


